version: "3.4"

services:
    ezpzos-database:
        image: linfeifu/ezpzosdatabase:latest
        environment:
            - DOTNET_ENVIRONMENT=Development
        volumes:
            - database:/var/opt/mssql/data/:nocopy
volumes:
    database:
